### ISSUE TITLE
Add RData File to datasets

### ISSUE THREAD

**Issue by stefanavey** [stefanavey/cbb-jamboree-intro-to-r#1]
Rob - I saw you fixed the URLs in the load call but you still have errors.

Looks like you still need to add the RData file to version control (git add).

**Comment by robertamezquita** [comment]
Yeah I noticed that when I pulled!! 

Get Outlook for iOS

On Mon, Oct 3, 2016 at 4:17 PM -0400, "Stefan Avey" notifications@github.com wrote:

Assigned #1 to @robertamezquita.

**Comment by robertamezquita** [comment]
Added datasets
